### ISSUE TITLE
Explanation for the algorithms

### ISSUE THREAD

**Issue by xmba15** [Livox-SDK/Livox_automatic_calibration#3]
@Livox-SDK Thank you guys for this repository. We would like to use this for our project, but can you provide a detailed explanation for the algorithms implemented here?

**Comment by Livox-SDK** [comment]
In order to solve the calibration problem, Livox provides an automatic calibration tool. This technology mainly relies on the isomorphic constraint assumption model of the environment to realize automatic calibration, and only needs to use the original point cloud data of the base LiDAR and target LiDAR. Our tool first mapping the environment by using the Base LiDAR data. Then we use the target LiDAR data to continuously iteratively register to the reconstructed map, relying on the constant assumption of the rigidity of geometric structure to continuously reduce the matching error until the algorithm converges And meets the rigidity invariant characteristic of the calibration matrix (six parallel lines). Finally, a consensus algorithm is used to calculate the final calibration matrix.

**Comment by xmba15** [comment]
@Livox-SDK thanks for the explanation. I would close the issue.
